/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventariois;

import javax.swing.JFrame;
import javax.swing.*;

/**
 *
 * @author Yohana Padilla
 */
public class Principal extends javax.swing.JFrame {


    /**
     * Creates new form Principal
     */
 
     public Principal(String rolUsuario) {
      
        initComponents();
        configurarRol(rolUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuUM = new javax.swing.JMenu();
        menuCategoria = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenu();
        menuTransacciones = new javax.swing.JMenu();
        menuConsultas = new javax.swing.JMenu();
        menuVentas = new javax.swing.JMenu();
        MenuClientes = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuUsuarios.setText("Usuarios");
        menuUsuarios.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuUsuariosMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuUsuarios);

        menuUM.setText("UM");
        menuUM.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuUMMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuUM);

        menuCategoria.setText("Categorias");
        menuCategoria.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuCategoriaMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuCategoria);

        menuProductos.setText("Productos");
        menuProductos.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuProductosMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuProductos);

        menuTransacciones.setText("Transacciones");
        menuTransacciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuTransaccionesMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuTransacciones);

        menuConsultas.setText("Consultas");
        menuConsultas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuConsultasMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuConsultas);

        menuVentas.setText("Ventas");
        menuVentas.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                menuVentasMenuSelected(evt);
            }
        });
        jMenuBar1.add(menuVentas);

        MenuClientes.setText("Clientes");
        MenuClientes.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                MenuClientesMenuSelected(evt);
            }
        });
        jMenuBar1.add(MenuClientes);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void menuUsuariosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuUsuariosMenuSelected
        Usuarios usuarios = new Usuarios();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                usuarios.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuUsuariosMenuSelected

    private void menuUMMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuUMMenuSelected
        Unidades unidades = new Unidades();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                unidades.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuUMMenuSelected

    private void menuCategoriaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuCategoriaMenuSelected
        Categorias categorias = new Categorias();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                categorias.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuCategoriaMenuSelected

    private void menuProductosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuProductosMenuSelected
        Productos producto = new Productos();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                producto.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuProductosMenuSelected

    private void menuTransaccionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuTransaccionesMenuSelected
        Transacciones transacciones = new Transacciones();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                transacciones.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuTransaccionesMenuSelected

    private void menuConsultasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuConsultasMenuSelected
        Consulta consulta = new Consulta();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                consulta.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuConsultasMenuSelected

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Imagen imagen = new Imagen();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                imagen.setVisible(true);
            }
        });
    }//GEN-LAST:event_formWindowOpened

    private void menuVentasMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_menuVentasMenuSelected
         // TODO add your handling code here:
         Ventas ventas = new Ventas();
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ventas.setVisible(true);
            }
        });
    }//GEN-LAST:event_menuVentasMenuSelected

    private void MenuClientesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_MenuClientesMenuSelected
        // TODO add your handling code here:
        Clientes clientePanel = new Clientes();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                clientePanel.setVisible(true);
            }
        });
    }//GEN-LAST:event_MenuClientesMenuSelected
  
    public void configurarRol(String rol) {
       if (rol.equalsIgnoreCase("Admin") || rol.equalsIgnoreCase("Supervisor")) {
           MenuClientes.setEnabled(true);
           menuVentas.setEnabled(true);
           menuCategoria.setEnabled(true);
           menuConsultas.setEnabled(true);
           menuProductos.setEnabled(true);
           menuTransacciones.setEnabled(true);
           menuUM.setEnabled(true);
           menuUsuarios.setEnabled(true);
       
        
    } else if (rol.equalsIgnoreCase("Cajero")) {
        MenuClientes.setEnabled(false);
        menuVentas.setEnabled(true);
        menuCategoria.setEnabled(false);
        menuConsultas.setEnabled(false);
        menuProductos.setEnabled(false);
        menuTransacciones.setEnabled(false);
        menuUM.setEnabled(false);
        menuUsuarios.setEnabled(false);
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String rolSimulado = "Cajero";
                Principal principal = new Principal(rolSimulado);
                principal.setExtendedState(JFrame.MAXIMIZED_BOTH);
                principal.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuClientes;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCategoria;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuTransacciones;
    private javax.swing.JMenu menuUM;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menuVentas;
    // End of variables declaration//GEN-END:variables
}
